[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && dotnet run --urls http://0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
